version: '3'
services:
  zookeeper:
    image: confluentinc/cp-zookeeper:latest
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181

  kafka:
    image: confluentinc/cp-kafka:latest
    environment:
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092
      KAFKA_AUTO_CREATE_TOPICS_ENABLE: "true"
    depends_on:
      - zookeeper

  producer:
    build: .
    entrypoint: ["python3", "/app/main.py"]
    command: ["produce", "--topic", "hello_topic", "--kafka", "kafka:9092", "--message", "Hello, World!"]
    depends_on:
      - kafka

    restart: on-failure

  consumer:
    build: .
    entrypoint: ["python3", "/app/main.py"]
    command: ["consume", "--topic", "hello_topic", "--kafka", "kafka:9092"]
    depends_on:
      - kafka
    restart: on-failure
